# Generated by Django 3.2 on 2023-05-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
